name: build

on:
  push:
    branches:
      - dev
      - rel/*
    tags: ["*"]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - dev
      - rel/*
    paths-ignore:
      - "**/*.md"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            os_name: macos
          - os: ubuntu-latest
            os_name: linux
          - os: windows-latest
            os_name: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "latest"

      - name: Set Build ID
        if: ${{ startsWith(github.ref, 'refs/pull/') == false }}
        shell: pwsh
        run: |
          $Now = (Get-Date).ToUniversalTime()
          $Hours = $Now.Hour * 4
          $QuarterHours = [Math]::Floor($Now.Minute / 15.0)
          $Revision = $Hours + $QuarterHours + 1
          $BuildId = $Now.ToString("yyyyMMdd") + "." + $Revision
          Write-Output "_ComputedOfficialBuildId=${BuildId}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build, Test and Package
        if: ${{ runner.os == 'Windows' }}
        run: eng\common\CIBuild.cmd -configuration Release -prepareMachine -integrationTest
        env:
          DOTNET_MULTILEVEL_LOOKUP: 0
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip

      - name: Build, Test and Package
        shell: pwsh
        if: ${{ runner.os != 'Windows' }}
        run: ./eng/common/cibuild.sh -configuration Release -prepareMachine -integrationTest
        env:
          DOTNET_MULTILEVEL_LOOKUP: 0
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          NUGET_XMLDOC_MODE: skip

      - name: Publish logs
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: logs-${{ matrix.os_name }}
          path: ./artifacts/log/Release

      - name: Publish NuGet packages
        uses: actions/upload-artifact@v1
        with:
          name: packages-${{ matrix.os_name }}
          path: ./artifacts/packages/Release/Shipping

      - name: Publish test results
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: testresults-${{ matrix.os_name }}
          path: ./artifacts/TestResults/Release

      - name: Push NuGet packages to NuGet.org
        run: dotnet nuget push "artifacts\packages\Release\Shipping\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
        if: ${{ github.repository_owner == 'JoyMoe' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && runner.os == 'Windows' }}
